# spring-petclinic-admin-server/Dockerfile
FROM openjdk:17-jdk-slim       
WORKDIR /app
# Copy jar đã build bằng Maven
COPY target/spring-petclinic-admin-server-*.jar app.jar
# port admin-server chạy
EXPOSE 9090                      
ENTRYPOINT ["java","-jar","/app.jar"]