# spring-petclinic-customers-service/Dockerfile
FROM openjdk:17-jdk-slim    
WORKDIR /app
# Copy jar đã build bằng Maven
COPY target/spring-petclinic-customers-service-*.jar app.jar
# port admin-server chạy
EXPOSE 8888                      
ENTRYPOINT ["java","-jar","/app.jar"]
