# spring-petclinic-genai-service/Dockerfile
FROM openjdk:17-jdk-slim        # base image
WORKDIR /app
# Copy jar đã build bằng Maven
COPY target/spring-petclinic-genai-service-*.jar app.jar
EXPOSE 8888                      # port admin-server chạy
ENTRYPOINT ["java","-jar","/app.jar"]
