# spring-petclinic-api-gateway/Dockerfile
FROM openjdk:17-jdk-slim      
WORKDIR /app
# Copy jar đã build bằng Maven
COPY target/spring-petclinic-api-gateway-*.jar app.jar
# port admin-server chạy
EXPOSE 8080                      
ENTRYPOINT ["java","-jar","/app.jar"]
