pipeline {
    agent any
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')  // bạn tạo trong Jenkins
        DOCKERHUB_USER = 'thainhat'
    }
    stages {
        stage('Build and Push Images') {
            matrix {
                axes {
                    axis {
                        name: 'SERVICE'
                        values: 'api-gateway', 'config-server', 'discovery-server', 'admin-server', 'customers-service', 'vets-service', 'visits-service', 'genai-service'
                    }
                }
                stages {
                    stage('Checkout') {
                        steps {
                            checkout scm
                        }
                    }
                    stage('Build Docker Image') {
                        steps {
                            script {
                                def image = "${DOCKERHUB_USER}/spring-petclinic-${SERVICE}:${env.GIT_COMMIT}"
                                sh """
                                    docker build -t ${image} spring-petclinic-${SERVICE}
                                """
                            }
                        }
                    }
                    stage('Push Docker Image') {
                        steps {
                            script {
                                def image = "${DOCKERHUB_USER}/spring-petclinic-${SERVICE}:${env.GIT_COMMIT}"
                                sh """
                                    echo "${DOCKERHUB_CREDENTIALS_PSW}" | docker login -u "${DOCKERHUB_CREDENTIALS_USR}" --password-stdin
                                    docker push ${image}
                                """
                            }
                        }
                    }
                }
            }
        }
    }
}
